[package]
name = "pce-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pce-gui"
path = "src/main.rs"

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
sunxi-fel = { workspace = true }
pce-fel = { workspace = true }
pce-recovery = { workspace = true }
rfd = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
linux-network = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }

tempfile = "3"
